//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meets
    {
        public int MeetId { get; set; }
        public int SportId { get; set; }
        public string MeetName { get; set; }
        public string Location { get; set; }
        public System.DateTime MeetDate { get; set; }
        public short Temperature { get; set; }
        public string WeatherNotes { get; set; }
        public string Gender { get; set; }
    
        public virtual Sports Sport { get; set; }
    }
}
