//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BurritoContainer : DbContext
    {
        public BurritoContainer()
            : base("name=BurritoContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sports> Sports { get; set; }
        public virtual DbSet<Meets> Meets { get; set; }
        public virtual DbSet<Athletes> Athletes { get; set; }
        public virtual DbSet<Coaches> Coaches { get; set; }
        public virtual DbSet<CoachedBy> CoachedBy { get; set; }
        public virtual DbSet<Roster> Rosters { get; set; }
    }
}
